### ISSUE TITLE
error during import

### ISSUE THREAD

**Issue by zhangxiutao** [magical-eda/MAGICAL#45]
Traceback (most recent call last):
  File "../../flow/python/Magical.py", line 10, in <module>
    import Params, MagicalDB, Flow
  File "/home/zxt/MAGICAL/flow/python/MagicalDB.py", line 8, in <module>
    import DesignDB
  File "/home/zxt/MAGICAL/flow/python/DesignDB.py", line 8, in <module>
    import magicalFlow
ImportError: /home/zxt/.local/lib/python3.8/site-packages/magicalFlow.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZTI12gzstreambase

**Comment by krzhu** [comment]
https://github.com/magical-eda/MAGICAL/commit/cdf4791b661eae588025bcb0671045853170b60d should already fix it.  And please be couteous and polite when opening new issue.
